#include "ImixMenu.hpp"
#include <algorithm>
#include <cstdio>
using namespace geode::prelude;
namespace {
constexpr ccColor3B BG{11,14,19},HEADER{17,21,28},SIDE{14,18,24},PANEL{23,29,38},TEXT{238,242,248},MUTED{133,145,160},ACCENT{92,184,255},ON{106,224,157};
CCLabelTTF* T(const char*s,float z,ccColor3B c){auto x=CCLabelTTF::create(s,"sans-serif",z);x->setColor(c);return x;}
CCMenuItemLabel* B(const char*s,CCObject*t,SEL_MenuHandler f,int tag=0){auto x=CCMenuItemLabel::create(T(s,12,TEXT),t,f);x->setTag(tag);return x;}
bool F(const char*k,bool d=false){return Mod::get()->getSavedValue<bool>(k,d);}
CCLayerColor* C(CCLayer*p,float y,float h){auto c=CCLayerColor::create({PANEL.r,PANEL.g,PANEL.b,255});c->setContentSize({p->getContentWidth()-44,h});c->setPosition({22,y});p->addChild(c);return c;}
void toggle(CCLayer*p,float y,const char*n,const char*d,const char*k,CCObject*t,int tag){auto c=C(p,y,42);auto l=T(n,11,TEXT);l->setAnchorPoint({0,1});l->setPosition({13,32});c->addChild(l);auto q=T(d,7,MUTED);q->setAnchorPoint({0,1});q->setPosition({13,16});c->addChild(q);auto m=CCMenu::create();m->setPosition({c->getContentWidth()-34,21});auto b=B(F(k)?"ON":"OFF",t,menu_selector(ImixMenu::onVisualToggle),tag);b->setScale(.67f);m->addChild(b);c->addChild(m);}
}
bool ImixMenu::init(){
 if(!Popup::init(520,335,"GJ_square01.png"))return false;auto win=CCDirector::sharedDirector()->getWinSize(),s=m_mainLayer->getContentSize();setScale(std::min(1.f,std::min(win.width*.88f/s.width,win.height*.76f/s.height)));
 auto r=CCLayerColor::create({BG.r,BG.g,BG.b,255});r->setContentSize(s);m_mainLayer->addChild(r,100);auto h=CCLayerColor::create({HEADER.r,HEADER.g,HEADER.b,255});h->setContentSize({s.width,58});h->setPosition({0,s.height-58});r->addChild(h);
 auto t=T("IMIX",21,TEXT);t->setAnchorPoint({0,.5f});t->setPosition({22,36});h->addChild(t);auto sub=T("CUSTOM GAMEPLAY LAB",8,MUTED);sub->setAnchorPoint({0,.5f});sub->setPosition({23,17});h->addChild(sub);
 auto side=CCLayerColor::create({SIDE.r,SIDE.g,SIDE.b,255});side->setContentSize({146,s.height-58});r->addChild(side);mContent=CCLayer::create();mContent->setContentSize({s.width-146,s.height-58});mContent->setPosition({146,0});r->addChild(mContent);
 mCategoryButtons=CCArray::create();mCategoryButtons->retain();auto menu=CCMenu::create();menu->setPosition({73,s.height-105});side->addChild(menu);const char* cats[]={"STARTPOS","PLAYER","VISUAL","PHYSICS","TOOLS"};for(int i=0;i<5;i++){auto b=B(cats[i],this,menu_selector(ImixMenu::onCategory),i);b->setPosition({0,76-i*43.f});menu->addChild(b);mCategoryButtons->addObject(b);}auto v=T("IMIX CORE",8,MUTED);v->setPosition({16,14});v->setAnchorPoint({0,0});side->addChild(v);selectCategory(0);return true;}
ImixMenu* ImixMenu::create(){auto x=new ImixMenu();if(x->init()){x->autorelease();return x;}delete x;return nullptr;}
void ImixMenu::onCategory(CCObject*s){int c=static_cast<CCNode*>(s)->getTag();if(c!=mSelectedCategory)selectCategory(c);}
void ImixMenu::animateCategoryButtons(){for(unsigned i=0;mCategoryButtons&&i<mCategoryButtons->count();i++){auto b=static_cast<CCMenuItemLabel*>(mCategoryButtons->objectAtIndex(i));b->stopAllActions();b->setColor(i==(unsigned)mSelectedCategory?ACCENT:TEXT);b->setScale(1);if(i==(unsigned)mSelectedCategory)b->runAction(CCSequence::create(CCScaleTo::create(.07f,1.06f),CCEaseSineOut::create(CCScaleTo::create(.16f,1)),nullptr));}}
void ImixMenu::animateContentIn(){if(!mContent)return;mContent->stopAllActions();mContent->setPositionX(mContent->getPositionX()+10);mContent->runAction(CCEaseSineOut::create(CCMoveBy::create(.18f,{-10,0})));}
void ImixMenu::selectCategory(int cat){mSelectedCategory=std::max(0,std::min(cat,4));mContent->removeAllChildrenWithCleanup(true);float h=mContent->getContentHeight();const char*titles[]={"Smart StartPos","Player Lab","Visual Lab","Physics Lab","Utilities"};auto title=T(titles[mSelectedCategory],19,TEXT);title->setAnchorPoint({0,1});title->setPosition({22,h-18});mContent->addChild(title);
 if(mSelectedCategory==0){auto c=C(mContent,h-132,68);auto l=T("SMART STARTPOS",12,TEXT);l->setPosition({14,49});c->addChild(l);auto d=T("Capture / restore your run position",8,MUTED);d->setPosition({14,30});c->addChild(d);auto m=CCMenu::create();m->setPosition({c->getContentWidth()-37,34});m->addChild(B(F("smart-startpos-enabled",true)?"ON":"OFF",this,menu_selector(ImixMenu::onSmartToggle)));c->addChild(m);auto a=C(mContent,h-209,57);auto i=T(F("startpos-valid")?"SLOT READY":"SLOT EMPTY",9,F("startpos-valid")?ON:MUTED);i->setPosition({14,37});a->addChild(i);auto am=CCMenu::create();am->setPosition({a->getContentWidth()-55,20});a->addChild(am);auto cp=B("CAPTURE",this,menu_selector(ImixMenu::onSmartAction),1);cp->setScale(.55);cp->setPositionY(10);am->addChild(cp);auto go=B("RESTORE",this,menu_selector(ImixMenu::onSmartAction),2);go->setScale(.55);go->setPositionY(-10);am->addChild(go);auto cl=B("CLEAR",this,menu_selector(ImixMenu::onSmartAction),0);cl->setScale(.55);cl->setPositionX(-43);am->addChild(cl);auto n=T("Runtime only • level data stays untouched",7,MUTED);n->setPosition({22,19});mContent->addChild(n);
 }else if(mSelectedCategory==1){toggle(mContent,h-132,"Ghost Player","Semi-transparent player","ghost-player",this,1);toggle(mContent,h-180,"Hide Player","Invisible sprite","hide-player",this,2);toggle(mContent,h-228,"Rainbow Player","Animated color cycle","rainbow-player",this,3);toggle(mContent,h-276,"Mirror Player","Horizontal flip","mirror-player",this,4);auto c=C(mContent,h-324,42);auto l=T("Player Scale",11,TEXT);l->setPosition({13,27});c->addChild(l);int s=Mod::get()->getSavedValue<int>("player-scale",100);char b[20];std::snprintf(b,sizeof(b),"%d%%",s);auto m=CCMenu::create();m->setPosition({c->getContentWidth()-40,21});m->addChild(B(b,this,menu_selector(ImixMenu::onPlayerScale)));c->addChild(m);
 }else if(mSelectedCategory==2){toggle(mContent,h-132,"Ghost Player","Transparency","ghost-player",this,1);toggle(mContent,h-180,"Hide Player","No player sprite","hide-player",this,2);toggle(mContent,h-228,"Rainbow Player","RGB animation","rainbow-player",this,3);toggle(mContent,h-276,"Mirror Player","Horizontal flip","mirror-player",this,4);toggle(mContent,h-324,"Spin Player","Continuous rotation","spin-player",this,5);
 }else if(mSelectedCategory==3){toggle(mContent,h-132,"Auto Jump","Automatic jump pulse","auto-jump",this,10);toggle(mContent,h-180,"Low Gravity","Local gravity reduction","low-gravity",this,11);toggle(mContent,h-228,"High Gravity","Local gravity increase","high-gravity",this,12);toggle(mContent,h-276,"Freeze Rotation","Lock player angle","freeze-rotation",this,13);toggle(mContent,h-324,"Phase Assist","Experimental collision bypass","phase-assist",this,14);
 }else{auto c=C(mContent,h-132,68);auto l=T("RESET EVERYTHING",12,TEXT);l->setPosition({14,49});c->addChild(l);auto d=T("Restore all Imix runtime values",8,MUTED);d->setPosition({14,30});c->addChild(d);auto m=CCMenu::create();m->setPosition({c->getContentWidth()-43,33});m->addChild(B("RESET",this,menu_selector(ImixMenu::onResetFeatures)));c->addChild(m);}
 animateCategoryButtons();animateContentIn();}
void ImixMenu::onSmartToggle(CCObject*){Mod::get()->setSavedValue("smart-startpos-enabled",!F("smart-startpos-enabled",true));selectCategory(0);}
void ImixMenu::onSmartAction(CCObject*s){int t=static_cast<CCNode*>(s)->getTag();if(t==1)Mod::get()->setSavedValue("startpos-request-capture",true);else if(t==2)Mod::get()->setSavedValue("startpos-request-teleport",true);else{Mod::get()->setSavedValue("startpos-valid",false);Mod::get()->setSavedValue("startpos-request-capture",false);}selectCategory(0);}
void ImixMenu::onVisualToggle(CCObject*s){int t=static_cast<CCNode*>(s)->getTag();const char*k=t==1?"ghost-player":t==2?"hide-player":t==3?"rainbow-player":t==4?"mirror-player":t==5?"spin-player":t==10?"auto-jump":t==11?"low-gravity":t==12?"high-gravity":t==13?"freeze-rotation":"phase-assist";Mod::get()->setSavedValue(k,!F(k));selectCategory(mSelectedCategory);}
void ImixMenu::onPlayerScale(CCObject*){int s=Mod::get()->getSavedValue<int>("player-scale",100)+10;if(s>140)s=60;Mod::get()->setSavedValue("player-scale",s);selectCategory(1);}
void ImixMenu::onResetFeatures(CCObject*){const char*ks[]={"ghost-player","hide-player","rainbow-player","mirror-player","spin-player","auto-jump","low-gravity","high-gravity","freeze-rotation","phase-assist","startpos-valid","startpos-request-capture","startpos-request-teleport"};for(auto k:ks)Mod::get()->setSavedValue(k,false);Mod::get()->setSavedValue("player-scale",100);selectCategory(0);}
