#include "ImixMenu.hpp"
#include <algorithm>
using namespace geode::prelude;
namespace { constexpr ccColor3B BG{14,17,22}, PANEL{25,30,38}, TEXT{238,241,247}, MUTED{139,148,162}, ACCENT{105,190,255};
CCLabelTTF* T(const char*s,float z,ccColor3B c){auto x=CCLabelTTF::create(s,"sans-serif",z);x->setColor(c);return x;}
CCMenuItemLabel* B(const char*s,CCObject*t,SEL_MenuHandler f,int tag=0){auto x=CCMenuItemLabel::create(T(s,13,TEXT),t,f);x->setTag(tag);return x;}
bool F(const char*k,bool d=false){return Mod::get()->getSavedValue<bool>(k,d);}
CCLayerColor* C(CCLayer*p,float y,float h){auto c=CCLayerColor::create({PANEL.r,PANEL.g,PANEL.b,255});c->setContentSize({p->getContentWidth()-44,h});c->setPosition({22,y});p->addChild(c);return c;}}

bool ImixMenu::init(){if(!Popup::init(500,315,"GJ_square01.png"))return false;auto w=CCDirector::sharedDirector()->getWinSize(),s=m_mainLayer->getContentSize();setScale(std::min(1.f,std::min(w.width*.86f/s.width,w.height*.72f/s.height)));auto r=CCLayerColor::create({BG.r,BG.g,BG.b,255});r->setContentSize(s);m_mainLayer->addChild(r,100);auto h=CCLayerColor::create({19,23,29,255});h->setContentSize({s.width,58});h->setPosition({0,s.height-58});r->addChild(h);auto t=T("IMIX",22,TEXT);t->setPosition({22,36});t->setAnchorPoint({0,.5f});h->addChild(t);auto sub=T("MOD CONTROL CENTER",9,MUTED);sub->setPosition({23,17});sub->setAnchorPoint({0,.5f});h->addChild(sub);mContent=CCLayer::create();mContent->setContentSize({s.width-142,s.height-58});mContent->setPosition({142,0});r->addChild(mContent);mCategoryButtons=CCArray::create();mCategoryButtons->retain();auto menu=CCMenu::create();menu->setPosition({71,s.height-150});r->addChild(menu);const char* cats[]={"StartPos","Player","Visual","Tools"};for(int i=0;i<4;i++){auto b=B(cats[i],this,menu_selector(ImixMenu::onCategory),i);b->setPosition({0,72-i*45.f});menu->addChild(b);mCategoryButtons->addObject(b);}selectCategory(0);return true;}
ImixMenu* ImixMenu::create(){auto x=new ImixMenu();if(x->init()){x->autorelease();return x;}delete x;return nullptr;}
void ImixMenu::onCategory(CCObject*s){int c=static_cast<CCNode*>(s)->getTag();if(c!=mSelectedCategory)selectCategory(c);}
void ImixMenu::animateCategoryButtons(){for(unsigned i=0;mCategoryButtons&&i<mCategoryButtons->count();i++){auto b=static_cast<CCMenuItemLabel*>(mCategoryButtons->objectAtIndex(i));b->setColor(i==(unsigned)mSelectedCategory?ACCENT:TEXT);}}
void ImixMenu::animateContentIn(){if(!mContent)return;mContent->stopAllActions();mContent->setPositionX(mContent->getPositionX()+8);mContent->runAction(CCEaseSineOut::create(CCMoveBy::create(.16,{-8,0})));}
void ImixMenu::selectCategory(int cat){mSelectedCategory=std::max(0,std::min(cat,3));mContent->removeAllChildrenWithCleanup(true);float h=mContent->getContentHeight();auto title=T(mSelectedCategory==0?"Smart StartPos":mSelectedCategory==1?"Player Cheats":mSelectedCategory==2?"Visual Cheats":"Tools",20,TEXT);title->setAnchorPoint({0,1});title->setPosition({22,h-20});mContent->addChild(title);
if(mSelectedCategory==0){auto c=C(mContent,h-137,82);auto l=T("Smart StartPos",14,TEXT);l->setPosition({15,62});c->addChild(l);auto d=T("Capture current player position",9,MUTED);d->setPosition({15,40});c->addChild(d);auto m=CCMenu::create();m->setPosition({c->getContentWidth()-42,25});m->addChild(B(F("smart-startpos-enabled",true)?"ON":"OFF",this,menu_selector(ImixMenu::onSmartToggle)));c->addChild(m);auto a=C(mContent,h-220,72);auto i=T(F("startpos-valid")?"Position saved":"No position saved",9,MUTED);i->setPosition({15,38});a->addChild(i);auto am=CCMenu::create();am->setPosition({a->getContentWidth()-55,22});a->addChild(am);auto cap=B("Capture",this,menu_selector(ImixMenu::onSmartAction),1);cap->setScale(.65);cap->setPositionY(12);am->addChild(cap);auto clr=B("Clear",this,menu_selector(ImixMenu::onSmartAction),0);clr->setScale(.65);clr->setPositionY(-12);am->addChild(clr);
}else if(mSelectedCategory==1||mSelectedCategory==2){const char*n[]={"Ghost Player","Hide Player","Rainbow Player"};const char*d[]={"50% opacity","Hide sprite","Animated RGB"};const char*k[]={"ghost-player","hide-player","rainbow-player"};for(int i=0;i<3;i++){auto c=C(mContent,h-137-i*55,48);auto l=T(n[i],12,TEXT);l->setPosition({13,30});c->addChild(l);auto q=T(d[i],8,MUTED);q->setPosition({13,14});c->addChild(q);auto m=CCMenu::create();m->setPosition({c->getContentWidth()-38,24});m->addChild(B(F(k[i])?"ON":"OFF",this,menu_selector(ImixMenu::onVisualToggle),i+1));c->addChild(m);}if(mSelectedCategory==1){auto c=C(mContent,h-302,48);auto l=T("Player Scale",12,TEXT);l->setPosition({13,30});c->addChild(l);auto m=CCMenu::create();m->setPosition({c->getContentWidth()-38,24});m->addChild(B("CHANGE",this,menu_selector(ImixMenu::onPlayerScale)));c->addChild(m);}}
else{auto c=C(mContent,h-137,82);auto l=T("Reset Features",14,TEXT);l->setPosition({15,55});c->addChild(l);auto m=CCMenu::create();m->setPosition({c->getContentWidth()-42,22});m->addChild(B("RESET",this,menu_selector(ImixMenu::onResetFeatures)));c->addChild(m);}animateCategoryButtons();animateContentIn();}
void ImixMenu::onSmartToggle(CCObject*){Mod::get()->setSavedValue("smart-startpos-enabled",!F("smart-startpos-enabled",true));selectCategory(0);}
void ImixMenu::onSmartAction(CCObject*s){Mod::get()->setSavedValue("smart-startpos-captured",static_cast<CCNode*>(s)->getTag()==1);selectCategory(0);}
void ImixMenu::onVisualToggle(CCObject*s){int t=static_cast<CCNode*>(s)->getTag();const char*k=t==1?"ghost-player":t==2?"hide-player":"rainbow-player";Mod::get()->setSavedValue(k,!F(k));selectCategory(mSelectedCategory);}
void ImixMenu::onPlayerScale(CCObject*){int s=Mod::get()->getSavedValue<int>("player-scale",100)+10;if(s>130)s=70;Mod::get()->setSavedValue("player-scale",s);selectCategory(1);}
void ImixMenu::onResetFeatures(CCObject*){Mod::get()->setSavedValue("ghost-player",false);Mod::get()->setSavedValue("hide-player",false);Mod::get()->setSavedValue("rainbow-player",false);Mod::get()->setSavedValue("smart-startpos-captured",false);Mod::get()->setSavedValue("startpos-valid",false);Mod::get()->setSavedValue("player-scale",100);selectCategory(0);}
