name: Build Geode Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: android
            runner: ubuntu-latest
            target: Android64
          - name: win
            runner: windows-latest
            target: Win64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Build Geode mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: latest
          target: ${{ matrix.target }}
          combine: true
